# Generated by Django 3.2.8 on 2021-10-26 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Recipe',
                'ordering': ['created'],
            },
        ),
    ]
